# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1726a05c12fe7d02c29ebb88a0a365f7bf4cf1a47a48db69e9fd9a4b3b597d4bdbb1737f78d355cea9712837f42bd10f95a103f45c62fc0841e074a10867326b

test:
  secret_key_base: e03033dba07f6d249f9d632861733fdda99441892d2843121d3872aa20d052deca51a1a20b3d4dca293716155bc443d4f82d0b8c8a2f14f32ef7a39de8fef338

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
